name: CustomSurvivalist
version: ${project.version}
main: me.simondmc.customsurvivalist.Main
api-version: 1.16
authors: [ SimonDMC ]
description: A Survivalist vs Hitmen plugin with no world border, but a debuff system instead!

commands:
  svh:
